name: Take Snap of Rendered Page

on:
  push:
    branches: [ main ]

jobs:
  snap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Installing build deps'
        run: npm i -g pnpm

      - name: 'Installing deps'
        run: pnpm i && npm i -g serve && npx --yes puppeteer browsers install chrome

      - name: 'Build Prodcution'
        run: pnpm build

      - name: 'Serve Prodcution Server'
        run: serve -s build -p 5173 &

      - name: 'Installing System Deps'
        run: sudo apt update -y && sudo apt install -y libgbm1

      - name: 'Take Snap'
        run: node puppeteer/snap.js

      - name: 'Upload report'
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: snap-of-homepage
          path: |
            homepage.png
