name: Take Snap of Rendered Page

on:
  push:
    branches: [ main ]

jobs:
  snap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Installing deps'
        run: yarn

      - name: 'Build Prodcution'
        run: yarn build

      - name: 'Serve Prodcution Server'
        run: serve -s build &

      - name: 'Take Snap'
        run: node puppeteer/snap.js

      - name: 'Upload report'
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: snap-of-homepage
          path: |
            homepage.png
